from sqlmodel import SQLModel, Field, create_engine, Session
from typing import Optional
from datetime import datetime

# SQLModel models for database tables

class DailyPick(SQLModel, table=True):
    """Daily stock picks generated by the AI system"""
    id: Optional[int] = Field(default=None, primary_key=True)
    date: str = Field(index=True, unique=True)
    picks_json: str  # JSON string of picks with analysis
    timestamp: str

class UserSession(SQLModel, table=True):
    """User sessions for chat and analysis"""
    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: str = Field(index=True, unique=True)
    user_id: Optional[str] = Field(default=None, index=True)
    created_at: str
    last_active: str

class NewsItem(SQLModel, table=True):
    """Market news articles"""
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str
    summary: str
    content: Optional[str] = None
    category: str = Field(index=True)  # market, stocks, economy, global
    source: str
    url: Optional[str] = None
    symbols: Optional[str] = None  # Comma-separated list of related symbols
    timestamp: str = Field(index=True)
    fetched_at: str


class Trade(SQLModel, table=True):
    """Individual trade records for tracking executed trades"""
    id: Optional[int] = Field(default=None, primary_key=True)
    date: str = Field(index=True)  # YYYY-MM-DD
    symbol: str = Field(index=True)
    direction: str  # LONG or SHORT
    entry_price: float
    exit_price: Optional[float] = None
    quantity: int
    entry_time: str
    exit_time: Optional[str] = None
    stop_loss: float
    take_profit: float
    realized_pnl: Optional[float] = None
    status: str = Field(default="OPEN", index=True)  # OPEN, CLOSED, STOPPED_OUT
    order_id: Optional[str] = None
    sl_order_id: Optional[str] = None
    exit_reason: Optional[str] = None  # TAKE_PROFIT, STOP_LOSS, MANUAL, TRAILING_STOP

# Database engine and session management
sqlite_url = "sqlite:///hagrid_ai.db"
engine = create_engine(sqlite_url, echo=False)

def create_db_and_tables():
    SQLModel.metadata.create_all(engine)

def get_session():
    with Session(engine) as session:
        yield session