"""
Pydantic models for the Fyers SDK.
"""

from broker.fyers.models.config import FyersConfig
from broker.fyers.models.auth import (
    TokenData,
    AuthCodeResponse,
    TokenResponse,
    RefreshTokenRequest,
    ValidateAuthCodeRequest,
    AuthState,
)
from broker.fyers.models.rate_limit import (
    RateLimitConfig,
    RateLimitState,
    RateLimitType,
    APICallRecord,
    DailyRateLimitRecord,
)
from broker.fyers.models.enums import (
    Exchange,
    Segment,
    InstrumentType,
    OrderType,
    OrderSide,
    OrderStatus,
    PositionSide,
    ProductType,
    OrderValidity,
    HoldingType,
    OrderSource,
)
from broker.fyers.models.responses import (
    ProfileData,
    ProfileResponse,
    FundItem,
    FundsResponse,
    HoldingItem,
    HoldingsOverall,
    HoldingsResponse,
    OrderItem,
    OrdersResponse,
    PositionItem,
    PositionsOverall,
    PositionsResponse,
    TradeItem,
    TradesResponse,
    OrderPlacementResponse,
    MultiOrderItemResponse,
    MultiOrderResponse,
    OrderModifyResponse,
    OrderCancelResponse,
    LogoutResponse,
    GenericResponse,
    HistoryResponse,
    QuoteData,
    QuotesResponse,
    MarketDepthLevel,
    MarketDepthData,
    MarketDepthResponse,
    MarketStatusItem,
    MarketStatusResponse,
    MarginCalculation,
    MarginResponse,
    GTTOrderItem,
    GTTOrdersResponse,
    OptionChainResponse,
)
from broker.fyers.models.orders import (
    SingleOrderRequest,
    ModifyOrderRequest,
    CancelOrderRequest,
    MultiLegOrderLeg,
    MultiLegOrderRequest,
    ExitPositionRequest,
    ConvertPositionRequest,
    create_market_order,
    create_limit_order,
    create_stop_order,
    create_stop_limit_order,
    create_bracket_order,
    create_cover_order,
)

__all__ = [
    # Config
    "FyersConfig",
    
    # Auth
    "TokenData",
    "AuthCodeResponse",
    "TokenResponse",
    "RefreshTokenRequest",
    "ValidateAuthCodeRequest",
    "AuthState",
    
    # Rate Limit
    "RateLimitConfig",
    "RateLimitState",
    "RateLimitType",
    "APICallRecord",
    "DailyRateLimitRecord",
    
    # Enums
    "Exchange",
    "Segment",
    "InstrumentType",
    "OrderType",
    "OrderSide",
    "OrderStatus",
    "PositionSide",
    "ProductType",
    "OrderValidity",
    "HoldingType",
    "OrderSource",
    
    # Responses
    "ProfileData",
    "ProfileResponse",
    "FundItem",
    "FundsResponse",
    "HoldingItem",
    "HoldingsOverall",
    "HoldingsResponse",
    "OrderItem",
    "OrdersResponse",
    "PositionItem",
    "PositionsOverall",
    "PositionsResponse",
    "TradeItem",
    "TradesResponse",
    "OrderPlacementResponse",
    "MultiOrderItemResponse",
    "MultiOrderResponse",
    "OrderModifyResponse",
    "OrderCancelResponse",
    "LogoutResponse",
    "GenericResponse",
    "HistoryResponse",
    "QuoteData",
    "QuotesResponse",
    "MarketDepthLevel",
    "MarketDepthData",
    "MarketDepthResponse",
    "MarketStatusItem",
    "MarketStatusResponse",
    "MarginCalculation",
    "MarginResponse",
    "GTTOrderItem",
    "GTTOrdersResponse",
    "OptionChainResponse",
    
    # Order Requests
    "SingleOrderRequest",
    "ModifyOrderRequest",
    "CancelOrderRequest",
    "MultiLegOrderLeg",
    "MultiLegOrderRequest",
    "ExitPositionRequest",
    "ConvertPositionRequest",
    
    # Helper Functions
    "create_market_order",
    "create_limit_order",
    "create_stop_order",
    "create_stop_limit_order",
    "create_bracket_order",
    "create_cover_order",
]